version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: ecomm-it-app
        container_name: ecomm-it-app
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        extra_hosts:
            - "ecomm-it-app.test:127.0.0.1"
        hostname: ecomm-it-app.test
        networks:
            - ecomm-it-app-test
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: ecomm-it-app-db
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./database/dbdata:/var/lib/mysql
        networks:
            - ecomm-it-app-test
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    ecomm-it-app-test:
        driver: bridge
volumes:
    sailmysql:
        driver: local
